# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "marimo",
#     "pandas",
#     "plotly"
# ]
# ///

import marimo

__generated_with = "0.21.1"
app = marimo.App(width="medium")

async with app.setup(hide_code=True):
    # imports
    import plotly.express as px
    import plotly.graph_objects as go
    import pandas as pd
    import marimo as mo
    import numpy as np
    from pathlib import Path
    import sys
    import types
    import importlib.util

    module_name = "my_utils"

    if sys.platform == "emscripten":
        from pyodide.http import pyfetch

        print("WASM detected: Fetching local modules...")
        # needs to be ../public because of how the assets dir is created during build
        response = await pyfetch("../public/my_utils.py")
        if not response.ok:
            print("Attempted to fetch:", response.url)
            raise RuntimeError(f"Failed to load my_utils.py. Status: {response.status}")

        source = await response.text()
        module = types.ModuleType(module_name)
        module.__file__ = "/virtual/my_utils.py"
        exec(compile(source, module.__file__, "exec"), module.__dict__)
        sys.modules[module_name] = module
        my_utils = module
        print("Successfully loaded my_utils.py!")
    else:
        # Local Python: load from apps/public/my_utils.py
        module_path = Path("./apps/public/my_utils.py").resolve()
        spec = importlib.util.spec_from_file_location(module_name, module_path)
        if spec is None or spec.loader is None:
            raise RuntimeError(f"Could not load module spec from {module_path}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[module_name] = module
        spec.loader.exec_module(module)
        my_utils = module
        print("Local Python environment detected. Loaded my_utils.py from public/.")

    my_utils.run_plotly_defaults()


@app.cell
def _():
    mo.md("""
    # Encodings aka 'that line means something'
    """)
    return


@app.cell
def _():
    mo.hstack([mo.md("**Use your titles to lead with the story**"), mo.md("\"Monthly Sales by Product, 2021-2025\" <br> vs. <br> \"March and April show seasonal drop in sales for Electronics every year, with 2024 being the worst\"")],gap=2,align="center",widths=[.3,.7])
    return


@app.cell
def _():
    mo.hstack([mo.md("**Use Madlibs dynamic text**"), mo.md("If it's dynamic/autogenerated, try the 'madlibs' approach: <br> **{month_year}** was the best performing month for **{category_x}** <br> **March 2023** was the best performing month for **Electronics**")],gap=2,align="center",widths=[.3,.7])
    return


@app.cell
def _():
    mo.hstack([mo.md("**Subtitles can (and should) add context about data/sources**"), mo.md("")],gap=2,align="center",widths=[.3,.7])
    return


@app.cell(hide_code=True)
async def _():
    _img = await my_utils.gh_pages_load_image("encodings/bar_1.png")
    mo.hstack([_img,mo.md("**Highlighting part of a Bar Chart**: Accent color one value and grey out the others")],gap=2,align="center",widths=[.3,.7])
    return


@app.cell
async def _():
    _img = await my_utils.gh_pages_load_image("encodings/bar_2.png")
    mo.hstack([_img,mo.md("**Highlighting two parts a Bar Chart**: Accent color two values to compare them to the one another other")],gap=2,align="center",widths=[.3,.7])
    return


@app.cell
async def _():
    _img = await my_utils.gh_pages_load_image("encodings/bar_high_disparity.png")
    mo.hstack([_img,mo.md("**Choose the chart type based on the data properties and the charactersitics of the data**: When there are high disparaties between categories, a bar chart can be hard to read. A lot of the bar here isn't doing much.")],gap=2,align="center",widths=[.5,.5])
    return


@app.cell
async def _():
    _img = await my_utils.gh_pages_load_image("encodings/scatter_high_disparity.png")
    mo.hstack([_img,mo.md("**Choose the chart type based on the data properties and the charactersitics of the data**: A scatter plot makes it easier to compare and uses less space to compare the distance between one category and the others.")],gap=2,align="center",widths=[.5,.5])
    return


@app.cell
async def _():
    _img = await my_utils.gh_pages_load_image("encodings/bar_non_zero_x.png")
    mo.hstack([_img,mo.md("**Start at Zero**: Truncating ranges deceives the reader. Here it looks like purple is 8 times greater than grey where as really it's about 2.5 times greater.")],gap=2,align="center",widths=[.5,.5])
    return


@app.cell
async def _():
    _img = await my_utils.gh_pages_load_image("encodings/bar_zero_x.png")
    mo.hstack([_img,mo.md("**Start at Zero**: Beginning at zero keeps it honest. We could start at `$35k` but then we'd lose the insight that purple is about 75% greater than grey.")],gap=2,align="center",widths=[.5,.5])
    return


if __name__ == "__main__":
    app.run()
